package wast:codec@0.1.0;

interface codec {
  use wast:types/types@0.1.0.{wast-component, wast-error};

  record component-files {
    wast-json: list<u8>,
    syms-en-yaml: option<list<u8>>,
  }

  /// Parse a `world.wit` and synthesize the initial `component-files` (empty
  /// `wast.json` + optional `syms.en.yaml`) populated with the world's
  /// exported / imported funcs and types.
  compile-wit: func(world-wit: list<u8>) -> result<component-files, wast-error>;
  read: func(wast-json: list<u8>, syms-en-yaml: option<list<u8>>) -> result<wast-component, wast-error>;
  write: func(world-wit: list<u8>, component: wast-component) -> result<component-files, wast-error>;
  merge: func(world-wit: list<u8>, full: component-files, partial: wast-component) -> result<component-files, wast-error>;
}

world codec-world {
  export codec;
}
