[tasks.build]
run = "cargo component build --workspace && pnpm install && pnpm build"

[tasks.test-component]
depends = ['build']
run = "RUST_MIN_STACK=33554432 cargo test --workspace --exclude wast-syntax-raw"

[tasks.test-ts]
depends = ['build']
run = "pnpm test"

[tasks.ci] # only dependencies to be run
description = 'Run CI tasks'
depends = ['build', 'test-component', 'test-ts']

[tools]
rust = "latest"
cargo-binstall = { version = "latest", depends = ["rust"] }
node = "24"
pnpm = "latest"
wasmtime = "latest"
