[tasks.build]
run = "cargo component build && pnpm install && pnpm build"

[tasks.test-component]
depends = ['build']
run = "cargo component test"

[tasks.test-ts]
depends = ['build']
run = "pnpm test"

[tasks.ci] # only dependencies to be run
description = 'Run CI tasks'
depends = ['build', 'test-component', 'test-ts']

[tools]
rust = "latest"
"cargo-binstall" = { version = "latest", depends = ["rust"] }
node = "latest"
pnpm = "latest"
wasmtime = "latest"
