package wast:generated;

interface generated-iface {
  resource counter {
    constructor(init: u32);
    get: func() -> u32;
    zero: static func() -> counter;
  }
}

world generated {
  export generated-iface;
}
