/**
 * Integration tests: partial-manager WASM component.
 * Exercises extract and merge on WastComponents.
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { loadPartialManager } from "../src/wasm-plugin.js";
import type { WastDb } from "../src/wast-db.js";
import type { SymsData } from "../src/wasm-plugin.js";

// Serialized body bytes for [Call { func_uid: "f2", args: [] }].
// Generated by the ts-like WASM plugin from_text for "run()".
// Format: postcard-encoded Vec<Instruction>.
const BODY_CALLING_F2 = [1, 6, 2, 102, 50, 0];

function makeFullDb(): { db: WastDb; syms: SymsData } {
  return {
    db: {
      funcs: [
        [
          "f1",
          {
            source: { Internal: "f1" },
            params: [["p1", "t1"]],
            result: "t1",
            body: BODY_CALLING_F2,
          },
        ],
        [
          "f2",
          {
            source: { Exported: "f2" },
            params: [],
            result: "t1",
            body: null,
          },
        ],
        [
          "f3",
          {
            source: { Imported: "f3" },
            params: [["p3", "t1"]],
            result: null,
            body: null,
          },
        ],
      ],
      types: [
        [
          "t1",
          {
            source: { Internal: "t1" },
            definition: { Primitive: "U32" },
          },
        ],
      ],
    },
    syms: {
      wit: [["f3", "imported_fn"]],
      internal: [
        ["f1", "calc"],
        ["f2", "run"],
        ["t1", "u32"],
      ],
      local: [
        ["p1", "x"],
        ["p3", "val"],
      ],
    },
  };
}

describe("partial-manager WASM: extract", () => {
  it("extracts a single target function", async () => {
    const pm = await loadPartialManager();
    const { db, syms } = makeFullDb();

    const result = pm.extract(db, syms, [{ sym: "f2", includeCaller: false }]);

    // Should contain f2
    const f2 = result.db.funcs.find(([uid]) => uid === "f2");
    assert.ok(f2, "should contain target f2");
    assert.ok("Exported" in f2![1].source, "f2 should be exported");
  });

  it("includes called functions as imported", async () => {
    const pm = await loadPartialManager();
    const { db, syms } = makeFullDb();

    // Extract f1 which calls f2 in its body
    const result = pm.extract(db, syms, [{ sym: "f1", includeCaller: false }]);

    const f1 = result.db.funcs.find(([uid]) => uid === "f1");
    const f2 = result.db.funcs.find(([uid]) => uid === "f2");
    assert.ok(f1, "should contain target f1");
    assert.ok(f2, "should include called f2");
    // f2 should be marked as imported (pulled in as dependency)
    assert.ok("Imported" in f2![1].source, "called func f2 should be imported in partial");
  });

  it("includes callers with include_caller flag", async () => {
    const pm = await loadPartialManager();
    const { db, syms } = makeFullDb();

    // Extract f2 with include_caller — f1 calls f2, so f1 should be included
    const result = pm.extract(db, syms, [{ sym: "f2", includeCaller: true }]);

    const f1 = result.db.funcs.find(([uid]) => uid === "f1");
    const f2 = result.db.funcs.find(([uid]) => uid === "f2");
    assert.ok(f2, "should contain target f2");
    assert.ok(f1, "should include caller f1");
  });

  it("includes referenced types", async () => {
    const pm = await loadPartialManager();
    const { db, syms } = makeFullDb();

    const result = pm.extract(db, syms, [{ sym: "f1", includeCaller: false }]);

    // f1 uses type t1 in params and result
    const t1 = result.db.types.find(([uid]) => uid === "t1");
    assert.ok(t1, "should include referenced type t1");
  });
});

describe("partial-manager WASM: merge", () => {
  it("merges a partial into full", async () => {
    const pm = await loadPartialManager();
    const { db: fullDb, syms: fullSyms } = makeFullDb();

    // Create a partial with just f1 (updated body)
    const partialDb: WastDb = {
      funcs: [
        [
          "f1",
          {
            source: { Internal: "f1" },
            params: [["p1", "t1"]],
            result: "t1",
            body: [0], // different body (Nop)
          },
        ],
      ],
      types: [],
    };
    const partialSyms: SymsData = {
      wit: [],
      internal: [["f1", "calc"]],
      local: [["p1", "x"]],
    };

    const result = pm.merge(partialDb, partialSyms, fullDb, fullSyms);

    // Should have all 3 original funcs
    assert.strictEqual(result.db.funcs.length, 3, "should have all funcs");

    // f1 should have updated body
    const f1 = result.db.funcs.find(([uid]) => uid === "f1");
    assert.ok(f1, "f1 should exist");
    assert.deepStrictEqual(f1![1].body, [0], "f1 body should be updated");

    // f2 and f3 should be unchanged
    const f2 = result.db.funcs.find(([uid]) => uid === "f2");
    assert.ok(f2, "f2 should still exist");
  });
});
