package wast:core@0.1.0;

interface syntax-plugin {
  use wast:types/types@0.1.0.{wast-component, wast-error};

  to-text: func(component: wast-component) -> result<string, list<wast-error>>;
  from-text: func(text: string, existing: wast-component) -> result<wast-component, list<wast-error>>;
}

interface partial-manager {
  use wast:types/types@0.1.0.{func-uid, wast-component, wast-error};

  record extract-target {
    sym: func-uid,
    include-caller: bool,
  }

  extract: func(full: wast-component, targets: list<extract-target>) -> wast-component;
  merge: func(partial: wast-component, full: wast-component) -> result<wast-component, list<wast-error>>;
}

world syntax-plugin-world {
  export syntax-plugin;
}

world partial-manager-world {
  export partial-manager;
}
