package wast:generated;

interface imported-iface {
  resource counter {
    constructor(init: u32);
    get: func() -> u32;
    zero: static func() -> counter;
  }
}

world generated {
  import imported-iface;
  export roundtrip: func(n: u32) -> u32;
  export via-zero: func() -> u32;
}
