name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Check & Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuboon/wast/wast-dev-container:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v6

      - name: Build components
        run: cargo component build --workspace

      - name: Check formatting
        run: |
          find . -name bindings.rs -path '*/src/*' | xargs rustfmt
          cargo fmt --check

      - name: Test
        run: cargo test --workspace

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
