name: CI

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:

jobs:
  check:
    name: Check & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/kuboon/wast/wast-dev-container:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@v6

    - run: |
        mise ls
        mise x -- node --version
        mise x -- cargo --version

    - run: cargo component build --workspace
    - run: cargo fmt --check

    - run: mise run ci
